### ISSUE TITLE
Does this work with Meteor 1.4.2?

### ISSUE THREAD

**Issue by jpmelnik** [thereactivestack-legacy/meteor-react-router-ssr#103]
I tried to install with the following three options but I cannot run meteor.
1. meteor add meteor-react-router-ssr
2. yarn add  react-router-ssr
3. npm install react-router-ssr

> Cannot find module 'meteor/reactrouter:react-router-ssr/lib/react-router-ssr.js'

**Comment by copleykj** [comment]
I can say for certain this works when adding via `meteor add` I can't specify yet about the other two at this time. I've just taken over maintenance and will have to look into the npm side of the package.

once added you'll just need to use a standard meteor package import.

```javascript
import { ReactRouterSSR } from 'meteor/reactrouter:react-router-ssr';

ReactRouterSSR.run(/*Routes here*/);

```
