### ISSUE TITLE
Not working with meteor package 1.7.1

### ISSUE THREAD

**Issue by SchlagerKhan** [thereactivestack-legacy/meteor-react-router-ssr#118]
Creating a new project including the latest meteor package (1.7.1, released 2 Aug 2017). Adding and running react-router-ssr gives the following errors: 

```
W20170809-14:51:24.010(2)? (STDERR) error on fast-rendering path: / ; error: TypeError: dynamics.slice is not a function
W20170809-14:51:24.095(2)? (STDERR)     at Object.Meteor.bindEnvironment (packages/meteor.js:1166:41)
W20170809-14:51:24.096(2)? (STDERR)     at PublishContext._.extend.onStop (packages/ddp-server/livedata_server.js:1226:23)
W20170809-14:51:24.097(2)? (STDERR)     at Context.processPublication (packages/staringatlights_fast-render.js:497:18)
W20170809-14:51:24.098(2)? (STDERR)     at packages/staringatlights_fast-render.js:313:15
W20170809-14:51:24.099(2)? (STDERR)     at Array.forEach (native)
W20170809-14:51:24.099(2)? (STDERR)     at Context.<anonymous> (packages/staringatlights_fast-render.js:310:18)
W20170809-14:51:24.100(2)? (STDERR)     at packages/staringatlights_fast-render.js:285:18
W20170809-14:51:24.101(2)? (STDERR)     at Array.forEach (native)
W20170809-14:51:24.102(2)? (STDERR)     at packages/staringatlights_fast-render.js:284:31
```

I'm not expecting any fix for this, but it might save a someone a headache. 

Downgrading to 1.7.0 works.

**Comment by copleykj** [comment]
Can you be more specific? I'm not sure what you mean by v1.7.1.

**Comment by SchlagerKhan** [comment]
Sorry for the ambiguity, I mean the internal core meteor package.

https://atmospherejs.com/meteor/meteor

**Comment by AirBorne04** [comment]
I am not facing this issue but maybe the fast render package got patched?
